ALTER TABLE [dbo].[NGUOI_DUNG] DROP CONSTRAINT IF EXISTS [CK_NGUOI_DUNG_VAI_TRO];
GO
ALTER TABLE [dbo].[NGUOI_DUNG] ADD CONSTRAINT [CK_NGUOI_DUNG_VAI_TRO] CHECK ([vai_tro] IN ('BLOGGER', 'ADMIN', 'PROVIDER', 'PROVIDER_PENDING', 'PROVIDER_APPROVED', 'TRAVELER', 'PREMIUM_TRAVELER'));
GO
