// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using ezTravel.Libs;

#nullable disable

namespace ezTravel.Libs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ezTravel.Entities.BinhLuan", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_binh_luan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_trinh");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaLichTrinh");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("BINH_LUAN");
                });

            modelBuilder.Entity("ezTravel.Entities.ChiTietDonDat", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<decimal>("DonGia")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("don_gia");

                    b.Property<int>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    b.Property<int>("MaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_don");

                    b.Property<DateOnly?>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly?>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<int>("SoLuong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_luong");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("thanh_tien");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaDon");

                    b.ToTable("CHI_TIET_DON_DAT");
                });

            modelBuilder.Entity("ezTravel.Entities.ChiTietLichTrinh", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_chi_tiet");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ghi_chu");

                    b.Property<TimeOnly?>("GioBatDau")
                        .HasColumnType("time")
                        .HasColumnName("gio_bat_dau");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_diem");

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_trinh");

                    b.Property<DateOnly?>("NgayTrongLichTrinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_trong_lich_trinh");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int")
                        .HasColumnName("thu_tu");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaLichTrinh");

                    b.ToTable("CHI_TIET_LICH_TRINH");
                });

            modelBuilder.Entity("ezTravel.Entities.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_gia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("binh_luan");

                    b.Property<int?>("MaDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_diem");

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_danh_gia")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte?>("SoSao")
                        .HasColumnType("tinyint")
                        .HasColumnName("so_sao");

                    b.HasKey("MaDanhGia");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaDichVu");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DANH_GIA");
                });

            modelBuilder.Entity("ezTravel.Entities.DanhMucDichVu", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<bool>("HienThi")
                        .HasColumnType("bit")
                        .HasColumnName("hien_thi");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_danh_muc");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DANH_MUC_DICH_VU");
                });

            modelBuilder.Entity("ezTravel.Entities.DiaDiem", b =>
                {
                    b.Property<int>("MaDiaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_diem");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaDiem"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("dia_chi");

                    b.Property<int?>("MaLoaiDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("ma_loai_dia_diem");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("QuocGia")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("quoc_gia");

                    b.Property<string>("TenDiaDiem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ten_dia_diem");

                    b.Property<string>("TinhThanh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("tinh_thanh");

                    b.Property<Geometry>("ToaDo")
                        .HasColumnType("geography")
                        .HasColumnName("toa_do");

                    b.HasKey("MaDiaDiem");

                    b.HasIndex("MaLoaiDiaDiem");

                    b.ToTable("DIA_DIEM");
                });

            modelBuilder.Entity("ezTravel.Entities.DichVu", b =>
                {
                    b.Property<int>("MaDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDichVu"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("gia_tien");

                    b.Property<int>("MaDanhMuc")
                        .HasColumnType("int")
                        .HasColumnName("ma_danh_muc");

                    b.Property<int>("MaDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_diem");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_toi_da");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("ten_dich_vu");

                    b.HasKey("MaDichVu");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaDiaDiem");

                    b.ToTable("DICH_VU");
                });

            modelBuilder.Entity("ezTravel.Entities.DonDat", b =>
                {
                    b.Property<int>("MaDon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_don");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDon"));

                    b.Property<int?>("MaGiamGia")
                        .HasColumnType("int")
                        .HasColumnName("ma_giam_gia");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_dat")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("tong_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChoDuyet")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaDon");

                    b.HasIndex("MaGiamGia");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DON_DAT");
                });

            modelBuilder.Entity("ezTravel.Entities.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_hinh_anh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("duong_dan");

                    b.Property<int?>("MaDiaDiem")
                        .HasColumnType("int")
                        .HasColumnName("ma_dia_diem");

                    b.Property<int?>("MaDichVu")
                        .HasColumnType("int")
                        .HasColumnName("ma_dich_vu");

                    b.HasKey("MaHinhAnh");

                    b.HasIndex("MaDiaDiem");

                    b.HasIndex("MaDichVu");

                    b.ToTable("HINH_ANH");
                });

            modelBuilder.Entity("ezTravel.Entities.LichTrinh", b =>
                {
                    b.Property<int>("MaLichTrinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_trinh");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichTrinh"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("DiemDen")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("diem_den");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mo_ta");

                    b.Property<decimal?>("NganSach")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("ngan_sach");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly>("NgayKetThuc")
                        .HasColumnType("date")
                        .HasColumnName("ngay_ket_thuc");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("SoNguoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("so_nguoi");

                    b.Property<string>("TenLichTrinh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("ten_lich_trinh");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Nhap")
                        .HasColumnName("trang_thai");

                    b.Property<string>("TrangThaiChiaSe")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("RiengTu")
                        .HasColumnName("trang_thai_chia_se");

                    b.HasKey("MaLichTrinh");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("LICH_TRINH");
                });

            modelBuilder.Entity("ezTravel.Entities.LoaiDiaDiem", b =>
                {
                    b.Property<int>("MaLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_loai");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLoai"));

                    b.Property<string>("BieuTuong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("bieu_tuong");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ten_loai");

                    b.HasKey("MaLoai");

                    b.ToTable("LOAI_DIA_DIEM");
                });

            modelBuilder.Entity("ezTravel.Entities.LuotThich", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<int>("MaLichTrinh")
                        .HasColumnType("int")
                        .HasColumnName("ma_lich_trinh");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao");

                    b.HasKey("MaNguoiDung", "MaLichTrinh");

                    b.HasIndex("MaLichTrinh");

                    b.ToTable("LUOT_THICH");
                });

            modelBuilder.Entity("ezTravel.Entities.MaGiamGia", b =>
                {
                    b.Property<int>("MaGiamGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_giam_gia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiamGiaId"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("MaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ma_code");

                    b.Property<DateOnly>("NgayBatDau")
                        .HasColumnType("date")
                        .HasColumnName("ngay_bat_dau");

                    b.Property<DateOnly>("NgayHetHan")
                        .HasColumnType("date")
                        .HasColumnName("ngay_het_han");

                    b.Property<decimal?>("PhanTramGiam")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("phan_tram_giam");

                    b.Property<int>("SoLuongDaDung")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_da_dung");

                    b.Property<int?>("SoLuongToiDa")
                        .HasColumnType("int")
                        .HasColumnName("so_luong_toi_da");

                    b.Property<decimal?>("SoTienGiam")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("so_tien_giam");

                    b.HasKey("MaGiamGiaId");

                    b.HasIndex("MaCode")
                        .IsUnique();

                    b.ToTable("MA_GIAM_GIA");
                });

            modelBuilder.Entity("ezTravel.Entities.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Avatar")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("avatar");

                    b.Property<bool?>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("da_xoa");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ho_ten");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("mat_khau");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date")
                        .HasColumnName("ngay_sinh");

                    b.Property<DateTime?>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("HoatDong")
                        .HasColumnName("trang_thai");

                    b.Property<string>("VaiTro")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Traveler")
                        .HasColumnName("vai_tro");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NGUOI_DUNG");
                });

            modelBuilder.Entity("ezTravel.Entities.ThanhToan", b =>
                {
                    b.Property<int>("MaThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thanh_toan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThanhToan"));

                    b.Property<int>("MaDon")
                        .HasColumnType("int")
                        .HasColumnName("ma_don");

                    b.Property<string>("MaGiaoDich")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("ma_giao_dich");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_thanh_toan");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phuong_thuc_thanh_toan");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("so_tien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ChoDuyet")
                        .HasColumnName("trang_thai");

                    b.HasKey("MaThanhToan");

                    b.HasIndex("MaDon");

                    b.HasIndex("MaGiaoDich")
                        .IsUnique()
                        .HasFilter("[ma_giao_dich] IS NOT NULL");

                    b.ToTable("THANH_TOAN");
                });

            modelBuilder.Entity("ezTravel.Entities.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ma_thong_bao");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaDoc")
                        .HasColumnType("bit")
                        .HasColumnName("da_doc");

                    b.Property<string>("LoaiThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("loai_thong_bao");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("ma_nguoi_dung");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("ngay_tao")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("noi_dung");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("tieu_de");

                    b.HasKey("MaThongBao");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("THONG_BAO");
                });

            modelBuilder.Entity("ezTravel.Entities.BinhLuan", b =>
                {
                    b.HasOne("ezTravel.Entities.LichTrinh", "LichTrinh")
                        .WithMany()
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LichTrinh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.ChiTietDonDat", b =>
                {
                    b.HasOne("ezTravel.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietDonDats")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ezTravel.Entities.DonDat", "DonDat")
                        .WithMany("ChiTietDonDats")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DichVu");

                    b.Navigation("DonDat");
                });

            modelBuilder.Entity("ezTravel.Entities.ChiTietLichTrinh", b =>
                {
                    b.HasOne("ezTravel.Entities.DiaDiem", "DiaDiem")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ezTravel.Entities.DichVu", "DichVu")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ezTravel.Entities.LichTrinh", "LichTrinh")
                        .WithMany("ChiTietLichTrinhs")
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("DichVu");

                    b.Navigation("LichTrinh");
                });

            modelBuilder.Entity("ezTravel.Entities.DanhGia", b =>
                {
                    b.HasOne("ezTravel.Entities.DiaDiem", "DiaDiem")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ezTravel.Entities.DichVu", "DichVu")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DiaDiem");

                    b.Navigation("DichVu");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.DiaDiem", b =>
                {
                    b.HasOne("ezTravel.Entities.LoaiDiaDiem", "LoaiDiaDiem")
                        .WithMany("DiaDiems")
                        .HasForeignKey("MaLoaiDiaDiem");

                    b.Navigation("LoaiDiaDiem");
                });

            modelBuilder.Entity("ezTravel.Entities.DichVu", b =>
                {
                    b.HasOne("ezTravel.Entities.DanhMucDichVu", "DanhMucDichVu")
                        .WithMany("DichVus")
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ezTravel.Entities.DiaDiem", "DiaDiem")
                        .WithMany("DichVus")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DanhMucDichVu");

                    b.Navigation("DiaDiem");
                });

            modelBuilder.Entity("ezTravel.Entities.DonDat", b =>
                {
                    b.HasOne("ezTravel.Entities.MaGiamGia", "MaGiamGia_Nav")
                        .WithMany("DonDats")
                        .HasForeignKey("MaGiamGia")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany("DonDats")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MaGiamGia_Nav");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.HinhAnh", b =>
                {
                    b.HasOne("ezTravel.Entities.DiaDiem", "DiaDiem")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaDiaDiem")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ezTravel.Entities.DichVu", "DichVu")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("MaDichVu")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DiaDiem");

                    b.Navigation("DichVu");
                });

            modelBuilder.Entity("ezTravel.Entities.LichTrinh", b =>
                {
                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany("LichTrinhs")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.LuotThich", b =>
                {
                    b.HasOne("ezTravel.Entities.LichTrinh", "LichTrinh")
                        .WithMany()
                        .HasForeignKey("MaLichTrinh")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LichTrinh");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.ThanhToan", b =>
                {
                    b.HasOne("ezTravel.Entities.DonDat", "DonDat")
                        .WithMany("ThanhToans")
                        .HasForeignKey("MaDon")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonDat");
                });

            modelBuilder.Entity("ezTravel.Entities.ThongBao", b =>
                {
                    b.HasOne("ezTravel.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("ezTravel.Entities.DanhMucDichVu", b =>
                {
                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("ezTravel.Entities.DiaDiem", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");

                    b.Navigation("DanhGias");

                    b.Navigation("DichVus");

                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("ezTravel.Entities.DichVu", b =>
                {
                    b.Navigation("ChiTietDonDats");

                    b.Navigation("ChiTietLichTrinhs");

                    b.Navigation("DanhGias");

                    b.Navigation("HinhAnhs");
                });

            modelBuilder.Entity("ezTravel.Entities.DonDat", b =>
                {
                    b.Navigation("ChiTietDonDats");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("ezTravel.Entities.LichTrinh", b =>
                {
                    b.Navigation("ChiTietLichTrinhs");
                });

            modelBuilder.Entity("ezTravel.Entities.LoaiDiaDiem", b =>
                {
                    b.Navigation("DiaDiems");
                });

            modelBuilder.Entity("ezTravel.Entities.MaGiamGia", b =>
                {
                    b.Navigation("DonDats");
                });

            modelBuilder.Entity("ezTravel.Entities.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("DonDats");

                    b.Navigation("LichTrinhs");
                });
#pragma warning restore 612, 618
        }
    }
}
